spring:
  datasource:
    url: jdbc:mariadb://database-test.cf88kudvdpgq.ap-southeast-1.rds.amazonaws.com:3306/Test
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update # ??? ? ??? ? ??? ?? ??
    properties:
      hibernate:
        show_sql: true # Hibernate? jpa? ???? sql? sysout? ? ???
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug  # ??? ? sql? ? ???
    org.hibernate.type: trace # ?? ????? ???


#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/jpashop
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create # ??? ? ??? ? ??? ?? ??
#    properties:
#      hibernate:
#        show_sql: true # Hibernate? jpa? ???? sql? sysout? ? ???
#        format_sql: true
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
